# -*- coding: utf-8 -*-
"""Assign3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GW-8aX8c7ecLzDMJIiSLhlh39-dPXGw_
"""

#Import packages
import pandas as pd
import numpy as np
trainDF = pd.read_csv('/content/sample_data/train.csv')
print(trainDF)

#Apply data cleaning to dataframe
trainDF.drop_duplicates(subset="f_27", keep ='first', inplace = True)
print(trainDF)



# apply second data cleaning
missing = trainDF.isnull()
print(missing)

trainDF = trainDF.dropna(axis=0)
print(trainDF)

from sklearn import datasets
svmModel = datasets.load_breast_cancer()
print(svmModel.data[5])

print(svmModel.data.shape)
print(svmModel.target)

from sklearn.model_selection import train_test_split
 
svmModel = datasets.load_breast_cancer()
 
X_train, X_test, y_train, y_test = train_test_split(svmModel.data, svmModel.target, test_size=0.4,random_state=109)

from sklearn import svm
#make classifier
cre = svm.SVC(kernel="linear")
#train model
cre.fit(X_train,y_train)
#predict the response
pred = cre.predict(X_test)

from sklearn import metrics
#check accuracy
print("accuracy:", metrics.accuracy_score(y_test,y_pred=pred))

print(trainDF)

trainDF.to_csv('assign.csv',index = False);