# -*- coding: utf-8 -*-
"""assign-2(spring-22).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TOjXrPeZ2wSaSPN_JCPLq71wQpC2dy9-
"""

import pandas as pd
import numpy as np

train_td = pd.read_csv('/content/sample_data/test.csv');

train_td

rId = train_td[['id']];

rId.insert(1,"target",0);

rId['target'] = np.random.rand(700000,1);

print(rId);
rId.to_csv('out.csv',index=False);